import type { CalendarData, CategoriesData, AreaMappingData, SourceData, LoadCalendarResult } from "../types";
import categoriesDataJson from "../../data/ebetsu/categories.json";
import areaMappingJson from "../../data/ebetsu/area-mapping.json";
import sourceDataJson from "../../data/ebetsu/source.json";
import bundledCalendarJson from "../../data/ebetsu/calendar.json";

export const MUNICIPALITY_CODE = "ebetsu";

export const categoriesData = categoriesDataJson as CategoriesData;
export const areaMappingData = areaMappingJson as AreaMappingData;
export const sourceData = sourceDataJson as SourceData;

/**
 * Ebetsu publishes no calendar API or CSV, only 13 area-group PDFs (re-published
 * every 6 months) with a real text layer. This snapshot was transcribed from those
 * PDFs (see data/ebetsu/source.json for the source URL) rather than generated by a
 * `npm run fetch:ebetsu` script, since there is nothing scriptable to fetch from —
 * re-transcription is a manual step when the city publishes the next 6-month batch.
 * There is no live-fetch fallback stage here (unlike sapporo/otaru): the bundled
 * snapshot is always what's shown.
 */
const bundledCalendar = bundledCalendarJson as CalendarData;

const CALENDAR_CACHE_KEY = "gomi-kore:ebetsu:calendar";

function readCachedCalendar(): CalendarData | null {
  try {
    const raw = localStorage.getItem(CALENDAR_CACHE_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as CalendarData;
  } catch {
    return null;
  }
}

export async function loadCalendar(): Promise<LoadCalendarResult> {
  const cached = readCachedCalendar();
  if (cached) {
    return { calendar: cached, source: "cache" };
  }
  return { calendar: bundledCalendar, source: "bundled" };
}

export function getCachedCalendar(): CalendarData | null {
  return readCachedCalendar();
}
