import type { CalendarData, CalendarDay, CategoriesData, AreaMappingData, SourceData, LoadCalendarResult } from "../types";
import categoriesDataJson from "../../data/otaru/categories.json";
import areaMappingJson from "../../data/otaru/area-mapping.json";
import sourceDataJson from "../../data/otaru/source.json";
import bundledCalendarJson from "../../data/otaru/calendar.json";

export const MUNICIPALITY_CODE = "otaru";

export const categoriesData = categoriesDataJson as CategoriesData;
export const areaMappingData = areaMappingJson as AreaMappingData;
export const sourceData = sourceDataJson as SourceData;

/**
 * Snapshot generated by `npm run fetch:otaru` (see scripts/fetch-otaru-calendar.mjs)
 * and committed to the repo. city.otaru.lg.jp does not send
 * Access-Control-Allow-Origin, so a live browser fetch is blocked by CORS;
 * this bundled copy is what most users will actually see the app render.
 */
const bundledCalendar = bundledCalendarJson as CalendarData;

const CALENDAR_CACHE_KEY = "gomi-kore:otaru:calendar";

// Minimal RFC4180-ish CSV parser (no external dependency), mirroring
// scripts/fetch-otaru-calendar.mjs so a live fetch (if CORS is ever
// unblocked, e.g. via a future proxy) parses identically to the snapshot.
function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += c;
      }
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\n") {
      row.push(field);
      field = "";
      rows.push(row);
      row = [];
    } else if (c === "\r") {
      // skip
    } else {
      field += c;
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows.filter((r) => r.some((cell) => cell.trim().length > 0));
}

function normalizeDate(raw: string): string {
  const [y, m, d] = raw.split("/");
  return `${y}-${m.padStart(2, "0")}-${d.padStart(2, "0")}`;
}

function normalizeCode(raw: string | undefined): string | null {
  const stripped = (raw ?? "").replace(/[\s　]+/g, "");
  return stripped.length > 0 ? stripped : null;
}

function parseCalendarCsv(csvText: string): CalendarDay[] {
  const rows = parseCsv(csvText);
  const header = rows[0];
  const areaColumnNames = header.slice(2);
  return rows
    .slice(1)
    .map((row) => {
      const areas: Record<string, string | null> = {};
      areaColumnNames.forEach((columnName, i) => {
        areas[columnName] = normalizeCode(row[2 + i]);
      });
      return { date: normalizeDate(row[0]), weekday: row[1], areas };
    })
    .sort((a, b) => a.date.localeCompare(b.date));
}

async function fetchCalendarFromSource(): Promise<CalendarData> {
  if (!sourceData.calendarCsvUrl) {
    throw new Error("Otaru source.json is missing calendarCsvUrl");
  }
  const response = await fetch(sourceData.calendarCsvUrl);
  if (!response.ok) {
    throw new Error(`Otaru calendar CSV request failed: ${response.status}`);
  }
  const buffer = await response.arrayBuffer();
  const csvText = new TextDecoder("shift_jis").decode(buffer);
  const days = parseCalendarCsv(csvText);
  return {
    municipalityCode: MUNICIPALITY_CODE,
    periodStart: sourceData.calendarPeriod.start,
    periodEnd: sourceData.calendarPeriod.end,
    days,
    fetchedAt: new Date().toISOString(),
  };
}

function readCachedCalendar(): CalendarData | null {
  try {
    const raw = localStorage.getItem(CALENDAR_CACHE_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as CalendarData;
  } catch {
    return null;
  }
}

function writeCachedCalendar(calendar: CalendarData): void {
  try {
    localStorage.setItem(CALENDAR_CACHE_KEY, JSON.stringify(calendar));
  } catch {
    // Storage may be unavailable (private mode, quota exceeded); caching is best-effort.
  }
}

/**
 * Loads the Otaru collection calendar: tries a fresh network fetch first,
 * falls back to the last cached copy, and finally falls back to the bundled
 * snapshot shipped with the app (see `bundledCalendar` above) so the app
 * always has data to show even on a first visit with no network access to
 * the city's CSV endpoint.
 */
export async function loadCalendar(): Promise<LoadCalendarResult> {
  try {
    const calendar = await fetchCalendarFromSource();
    writeCachedCalendar(calendar);
    return { calendar, source: "network" };
  } catch {
    const cached = readCachedCalendar();
    if (cached) {
      return { calendar: cached, source: "cache" };
    }
    return { calendar: bundledCalendar, source: "bundled" };
  }
}

export function getCachedCalendar(): CalendarData | null {
  return readCachedCalendar();
}
