import type {
  CalendarData,
  CalendarDay,
  CategoriesData,
  AreaMappingData,
  SourceData,
  LoadCalendarResult,
  ItemDictionaryData,
} from "../types";
import categoriesDataJson from "../../data/sapporo/categories.json";
import areaMappingJson from "../../data/sapporo/area-mapping.json";
import sourceDataJson from "../../data/sapporo/source.json";
import bundledCalendarJson from "../../data/sapporo/calendar.json";
import itemDictionaryJson from "../../data/sapporo/item-dictionary.json";

export const MUNICIPALITY_CODE = "sapporo";

export const categoriesData = categoriesDataJson as CategoriesData;
export const areaMappingData = areaMappingJson as AreaMappingData;
export const sourceData = sourceDataJson as SourceData;
/**
 * Generated by `npm run fetch:sapporo-dict` (see
 * scripts/fetch-sapporo-item-dictionary.mjs) from the City of Sapporo's
 * 家庭ごみ50音分別辞典, reproduced with the city's permission (see
 * sourceData.itemDictionaryCreditText) — unlike calendar.json, this is not
 * CC-BY data.
 */
export const itemDictionaryData = itemDictionaryJson as ItemDictionaryData;

/**
 * Snapshot generated by `npm run fetch:sapporo` (see scripts/fetch-sapporo-calendar.mjs)
 * and committed to the repo. ckan.pf-sapporo.jp does not send
 * Access-Control-Allow-Origin, so a live browser fetch is blocked by CORS;
 * this bundled copy is what most users will actually see the app render.
 */
const bundledCalendar = bundledCalendarJson as CalendarData;

const CALENDAR_CACHE_KEY = "gomi-kore:sapporo:calendar";

type CkanDatastoreSearchResponse = {
  success: boolean;
  result: {
    records: Record<string, unknown>[];
    total: number;
  };
};

function buildDatastoreUrl(resourceId: string, limit: number): string {
  // Sapporo's source.json always populates the CKAN-specific fields (unlike CSV-download-style sources).
  const url = new URL(sourceData.apiBaseUrl!);
  url.searchParams.set("resource_id", resourceId);
  url.searchParams.set("limit", String(limit));
  return url.toString();
}

function parseCalendarRecord(record: Record<string, unknown>): CalendarDay {
  const date = String(record["日付"]).slice(0, 10); // "2025-10-01T00:00:00" -> "2025-10-01"
  const weekday = String(record["曜"]);
  const areas: Record<string, string | null> = {};
  for (const area of areaMappingData.areas) {
    const raw = record[area.columnName];
    areas[area.columnName] = raw === null || raw === undefined ? null : String(raw);
  }
  return { date, weekday, areas };
}

async function fetchCalendarFromApi(): Promise<CalendarData> {
  const url = buildDatastoreUrl(sourceData.calendarResourceId!, 400);
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Sapporo calendar API request failed: ${response.status}`);
  }
  const json = (await response.json()) as CkanDatastoreSearchResponse;
  if (!json.success) {
    throw new Error("Sapporo calendar API returned success=false");
  }
  const days = json.result.records.map(parseCalendarRecord).sort((a, b) => a.date.localeCompare(b.date));
  return {
    municipalityCode: MUNICIPALITY_CODE,
    periodStart: sourceData.calendarPeriod.start,
    periodEnd: sourceData.calendarPeriod.end,
    days,
    fetchedAt: new Date().toISOString(),
  };
}

function readCachedCalendar(): CalendarData | null {
  try {
    const raw = localStorage.getItem(CALENDAR_CACHE_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as CalendarData;
  } catch {
    return null;
  }
}

function writeCachedCalendar(calendar: CalendarData): void {
  try {
    localStorage.setItem(CALENDAR_CACHE_KEY, JSON.stringify(calendar));
  } catch {
    // Storage may be unavailable (private mode, quota exceeded); caching is best-effort.
  }
}

/**
 * Loads the Sapporo collection calendar: tries a fresh network fetch first,
 * falls back to the last cached copy, and finally falls back to the bundled
 * snapshot shipped with the app (see `bundledCalendar` above) so the app
 * always has data to show even on a first visit with no network access to
 * the CKAN API.
 */
export async function loadCalendar(): Promise<LoadCalendarResult> {
  try {
    const calendar = await fetchCalendarFromApi();
    writeCachedCalendar(calendar);
    return { calendar, source: "network" };
  } catch {
    const cached = readCachedCalendar();
    if (cached) {
      return { calendar: cached, source: "cache" };
    }
    return { calendar: bundledCalendar, source: "bundled" };
  }
}

export function getCachedCalendar(): CalendarData | null {
  return readCachedCalendar();
}
